[2025-04-01T19:15:28.032+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-01T19:15:28.073+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.task1 manual__2025-04-01T19:15:24.024891+00:00 [queued]>
[2025-04-01T19:15:28.080+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.task1 manual__2025-04-01T19:15:24.024891+00:00 [queued]>
[2025-04-01T19:15:28.080+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-04-01T19:15:28.088+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task1> on 2025-04-01 19:15:24.024891+00:00
[2025-04-01T19:15:28.094+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'task1', 'manual__2025-04-01T19:15:24.024891+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpx58_meno']
[2025-04-01T19:15:28.098+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5873) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-01T19:15:28.099+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask task1
[2025-04-01T19:15:28.099+0000] {standard_task_runner.py:72} INFO - Started process 5874 to run task
[2025-04-01T19:15:28.275+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.task1 manual__2025-04-01T19:15:24.024891+00:00 [running]> on host 7d980c7fabe2
[2025-04-01T19:15:34.317+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='grypton' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T19:15:24.024891+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T19:15:24.024891+00:00'
[2025-04-01T19:15:34.324+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-01T19:15:34.383+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-01T19:15:34.392+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Hello World!!!, this is the very first dag'"]
[2025-04-01T19:15:34.406+0000] {subprocess.py:99} INFO - Output:
[2025-04-01T19:15:34.432+0000] {subprocess.py:106} INFO - Hello World!!!, this is the very first dag
[2025-04-01T19:15:34.438+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-01T19:15:34.528+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-01T19:15:34.533+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=task1, run_id=manual__2025-04-01T19:15:24.024891+00:00, execution_date=20250401T191524, start_date=20250401T191528, end_date=20250401T191534
[2025-04-01T19:15:34.668+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-01T19:15:34.719+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-01T19:15:34.720+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
