[2025-04-02T02:52:19.728+0000] {processor.py:186} INFO - Started process (PID=9838) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T02:52:19.729+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T02:52:19.730+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:52:19.729+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T02:52:19.740+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:52:19.737+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 185
    #     task1 >> task2 # task1.set_downstream(task2)
                                                      ^
IndentationError: expected an indented block after 'with' statement on line 15
[2025-04-02T02:52:19.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T02:52:19.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.032 seconds
[2025-04-02T02:52:50.102+0000] {processor.py:186} INFO - Started process (PID=9849) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T02:52:50.103+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T02:52:50.105+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:52:50.104+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T02:52:50.118+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:52:50.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 185
    #     task1 >> task2 # task1.set_downstream(task2)
                                                      ^
IndentationError: expected an indented block after 'with' statement on line 15
[2025-04-02T02:52:50.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T02:52:50.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.044 seconds
[2025-04-02T02:53:20.434+0000] {processor.py:186} INFO - Started process (PID=9860) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T02:53:20.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T02:53:20.437+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:53:20.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T02:53:20.453+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:53:20.450+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 185
    #     task1 >> task2 # task1.set_downstream(task2)
                                                      ^
IndentationError: expected an indented block after 'with' statement on line 15
[2025-04-02T02:53:20.453+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T02:53:20.467+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.042 seconds
[2025-04-02T02:53:50.773+0000] {processor.py:186} INFO - Started process (PID=9871) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T02:53:50.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T02:53:50.777+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:53:50.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T02:53:50.789+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:53:50.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 185
    #     task1 >> task2 # task1.set_downstream(task2)
                                                      ^
IndentationError: expected an indented block after 'with' statement on line 15
[2025-04-02T02:53:50.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T02:53:50.807+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.044 seconds
[2025-04-02T02:54:21.174+0000] {processor.py:186} INFO - Started process (PID=9882) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T02:54:21.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T02:54:21.176+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:54:21.176+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T02:54:21.186+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:54:21.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 185
    #     task1 >> task2 # task1.set_downstream(task2)
                                                      ^
IndentationError: expected an indented block after 'with' statement on line 15
[2025-04-02T02:54:21.186+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T02:54:21.200+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.033 seconds
[2025-04-02T02:54:56.774+0000] {processor.py:186} INFO - Started process (PID=9893) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T02:54:56.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T02:54:56.820+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:54:56.809+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T02:54:56.958+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:54:56.925+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 185
    #     task1 >> task2 # task1.set_downstream(task2)
                                                      ^
IndentationError: expected an indented block after 'with' statement on line 15
[2025-04-02T02:54:56.982+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T02:54:57.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 4.244 seconds
[2025-04-02T02:55:28.024+0000] {processor.py:186} INFO - Started process (PID=9904) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T02:55:28.025+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T02:55:28.027+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:55:28.026+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T02:55:28.040+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:55:28.037+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 185
    #     task1 >> task2 # task1.set_downstream(task2)
                                                      ^
IndentationError: expected an indented block after 'with' statement on line 15
[2025-04-02T02:55:28.040+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T02:55:28.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.047 seconds
[2025-04-02T02:55:49.316+0000] {processor.py:186} INFO - Started process (PID=9915) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T02:55:49.317+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T02:55:49.320+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:55:49.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T02:55:49.373+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T02:55:49.588+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:55:49.588+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T02:55:49.616+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:55:49.616+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2025-04-02 00:00:00+00:00, run_after=2025-04-03 00:00:00+00:00
[2025-04-02T02:55:49.631+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.326 seconds
[2025-04-02T02:56:23.000+0000] {processor.py:186} INFO - Started process (PID=9927) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T02:56:23.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T02:56:23.739+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:56:23.719+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T02:56:24.085+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T02:56:30.507+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:56:30.496+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T02:56:31.168+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:56:31.164+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2025-04-02 00:00:00+00:00, run_after=2025-04-03 00:00:00+00:00
[2025-04-02T02:56:32.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 12.042 seconds
[2025-04-02T02:57:04.791+0000] {processor.py:186} INFO - Started process (PID=9939) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T02:57:04.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T02:57:04.806+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:57:04.803+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T02:57:05.002+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T02:57:05.961+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:57:05.949+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T02:57:06.076+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:57:06.073+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2025-04-02 00:00:00+00:00, run_after=2025-04-03 00:00:00+00:00
[2025-04-02T02:57:08.847+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 4.092 seconds
[2025-04-02T02:57:59.248+0000] {processor.py:186} INFO - Started process (PID=9946) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T02:57:59.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T02:58:00.957+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:58:00.523+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T02:58:07.113+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T02:58:40.908+0000] {processor.py:186} INFO - Started process (PID=9949) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T02:58:40.910+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T02:58:40.919+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:58:40.916+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T02:58:40.953+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T02:58:40.989+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:58:40.988+0000] {taskinstance.py:3315} ERROR - {'DAG Id': 'first_dag', 'Task Id': 'get_name', 'Run Id': 'manual__2025-04-02T02:56:45.687884+00:00', 'Hostname': '7d980c7fabe2'}
[2025-04-02T02:58:41.067+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:58:41.066+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=get_name, run_id=manual__2025-04-02T02:56:45.687884+00:00, execution_date=20250402T025645, start_date=20250402T025705, end_date=20250402T025841
[2025-04-02T02:58:41.184+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:58:41.184+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: first_dag.get_name manual__2025-04-02T02:56:45.687884+00:00 [up_for_retry]> in state up_for_retry
[2025-04-02T02:58:41.217+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:58:41.217+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T02:58:41.236+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:58:41.236+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2025-04-02 00:00:00+00:00, run_after=2025-04-03 00:00:00+00:00
[2025-04-02T02:58:41.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.379 seconds
[2025-04-02T02:58:54.295+0000] {processor.py:186} INFO - Started process (PID=9954) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T02:58:54.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T02:58:54.307+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:58:54.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T02:58:54.349+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T02:58:54.549+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:58:54.548+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T02:58:54.573+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:58:54.572+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2025-04-02 00:00:00+00:00, run_after=2025-04-03 00:00:00+00:00
[2025-04-02T02:58:54.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.348 seconds
[2025-04-02T02:59:24.765+0000] {processor.py:186} INFO - Started process (PID=9965) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T02:59:24.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T02:59:24.769+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:59:24.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T02:59:24.791+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T02:59:24.885+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:59:24.884+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T02:59:24.893+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:59:24.893+0000] {dag.py:3262} INFO - Creating ORM DAG for first_dag
[2025-04-02T02:59:24.898+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:59:24.898+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2025-04-02 00:00:00+00:00, run_after=2025-04-03 00:00:00+00:00
[2025-04-02T02:59:24.905+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.152 seconds
[2025-04-02T02:59:57.022+0000] {processor.py:186} INFO - Started process (PID=9982) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T02:59:57.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T02:59:57.531+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:59:57.528+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T02:59:57.662+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T02:59:57.766+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:59:57.763+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T02:59:57.889+0000] {logging_mixin.py:190} INFO - [2025-04-02T02:59:57.884+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2025-04-02 00:00:00+00:00, run_after=2025-04-03 00:00:00+00:00
[2025-04-02T02:59:58.797+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 2.005 seconds
[2025-04-02T03:00:08.163+0000] {processor.py:186} INFO - Started process (PID=9993) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T03:00:08.164+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T03:00:08.166+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:00:08.165+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T03:00:08.202+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T03:00:08.259+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:00:08.259+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T03:00:08.281+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:00:08.281+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2025-04-02 00:00:00+00:00, run_after=2025-04-03 00:00:00+00:00
[2025-04-02T03:00:08.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.145 seconds
[2025-04-02T03:00:41.202+0000] {processor.py:186} INFO - Started process (PID=10010) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T03:00:41.210+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T03:00:41.221+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:00:41.212+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T03:00:41.435+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T03:00:43.182+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:00:43.153+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T03:00:53.873+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:00:53.867+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2025-04-02 00:00:00+00:00, run_after=2025-04-03 00:00:00+00:00
[2025-04-02T03:00:54.988+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 13.852 seconds
[2025-04-02T03:01:14.581+0000] {processor.py:186} INFO - Started process (PID=10021) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T03:01:14.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T03:01:14.585+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:01:14.584+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T03:01:14.595+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:01:14.593+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 163
    
    ^
IndentationError: expected an indented block after 'with' statement on line 15
[2025-04-02T03:01:14.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T03:01:14.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.054 seconds
[2025-04-02T03:01:45.073+0000] {processor.py:186} INFO - Started process (PID=10031) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T03:01:45.085+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T03:01:45.101+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:01:45.096+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T03:01:45.306+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:01:45.249+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 163
    
    ^
IndentationError: expected an indented block after 'with' statement on line 15
[2025-04-02T03:01:45.350+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T03:01:48.276+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 3.233 seconds
[2025-04-02T03:02:18.690+0000] {processor.py:186} INFO - Started process (PID=10042) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T03:02:18.690+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T03:02:18.692+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:02:18.691+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T03:02:18.702+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:02:18.699+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 163
    
    ^
IndentationError: expected an indented block after 'with' statement on line 15
[2025-04-02T03:02:18.702+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T03:02:18.724+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.043 seconds
[2025-04-02T03:02:49.009+0000] {processor.py:186} INFO - Started process (PID=10053) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T03:02:49.010+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T03:02:49.012+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:02:49.012+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T03:02:49.024+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:02:49.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 163
    
    ^
IndentationError: expected an indented block after 'with' statement on line 15
[2025-04-02T03:02:49.024+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T03:02:49.044+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.045 seconds
[2025-04-02T03:03:03.188+0000] {processor.py:186} INFO - Started process (PID=10058) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T03:03:03.190+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T03:03:03.192+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:03:03.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T03:03:03.216+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T03:03:03.330+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:03:03.330+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T03:03:03.346+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:03:03.346+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2025-04-02 00:00:00+00:00, run_after=2025-04-03 00:00:00+00:00
[2025-04-02T03:03:03.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.185 seconds
[2025-04-02T03:03:37.618+0000] {processor.py:186} INFO - Started process (PID=10069) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T03:03:37.629+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T03:03:37.648+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:03:37.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T03:03:37.748+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T03:03:41.010+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:03:41.008+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T03:03:41.023+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:03:41.023+0000] {dag.py:3262} INFO - Creating ORM DAG for first_dag
[2025-04-02T03:03:41.032+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:03:41.032+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2025-04-02 00:00:00+00:00, run_after=2025-04-03 00:00:00+00:00
[2025-04-02T03:03:41.052+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 6.616 seconds
[2025-04-02T03:04:11.869+0000] {processor.py:186} INFO - Started process (PID=10086) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T03:04:11.870+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T03:04:11.872+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:04:11.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T03:04:11.896+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T03:04:11.928+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:04:11.927+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T03:04:11.944+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:04:11.944+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2025-04-02 00:00:00+00:00, run_after=2025-04-03 00:00:00+00:00
[2025-04-02T03:04:11.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.096 seconds
[2025-04-02T03:04:43.370+0000] {processor.py:186} INFO - Started process (PID=10097) to work on /opt/airflow/dags/first_dag.py
[2025-04-02T03:04:43.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-04-02T03:04:43.840+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:04:43.658+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-04-02T03:04:44.380+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-04-02T03:04:44.671+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:04:44.659+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T03:04:45.372+0000] {logging_mixin.py:190} INFO - [2025-04-02T03:04:45.370+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2025-04-02 00:00:00+00:00, run_after=2025-04-03 00:00:00+00:00
[2025-04-02T03:04:45.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 2.691 seconds
